[tox]
envlist =
    py{39,310,311,312,313,314}-test{,-alldeps,-devdeps}{,-cov}
    py{39,310,311,312,313,314}-test-numpy{120,123}
    py{39,310,311,312,313,314}-test-astropy{52}
    build_docs
    linkcheck
    codestyle
requires =
    setuptools >= 30.3.0
    pip >= 19.3.1

isolated_build = true

[testenv]
description = run tests

# Pass through the following environment variables which may be needed for the CI
passenv = HOME, WINDIR, LC_ALL, LC_CTYPE, CC, CI, TRAVIS

# Run the tests in a temporary directory to make sure that we don't import
# this package from the source tree
changedir = .tmp/{envname}

# The following indicates which extras_require from setup.cfg will be installed
extras =
    test
    alldeps: docs

# The following provides some specific pinnings for key packages
deps =
    numpy120: numpy==1.20.*
    numpy123: numpy==1.23.*
    numpy2: numpy==2.0.*

    astropy52: astropy==5.2.*

    stdatamodels; python_version >= "3.11"

    devdeps: git+https://github.com/numpy/numpy.git#egg=numpy
    devdeps: git+https://github.com/astropy/astropy.git#egg=astropy

commands =
    pip freeze

    cov: pytest --pyargs astrocut --cov=astrocut --cov-config={toxinidir}/setup.cfg --cov-report=term-missing --cov-report=xml:{toxinidir}/coverage.xml {toxinidir}/astrocut {toxinidir}/docs {posargs}

    !cov: pytest --pyargs astrocut {toxinidir}/astrocut {toxinidir}/docs {posargs}

[testenv:build_docs]
changedir = docs
description = invoke sphinx-build to build the HTML docs
extras = docs
deps = 
    sphinx_rtd_theme
    matplotlib  # Sphinx uses matplotlib for plot_directive extension
commands =
    pip freeze
    sphinx-build -W -b html . _build/html

[testenv:linkcheck]
changedir = docs
description = check the links in the HTML docs
extras = docs
commands =
    pip freeze
    sphinx-build -W -b linkcheck . _build/html

[testenv:codestyle]
skip_install = true
changedir = .
description = check code style, e.g. with ruff
deps = ruff
commands =
    ruff check .
    ruff format --check .