---
name: Building & Publishing to Test PyPI
    
on:
    push:
      branches: ["*"]

permissions:
  contents: read
  id-token: read

jobs:
    make_tag:
        runs-on: ubuntu-latest
    
        # We want a new tag to be made ONLY if we are ready to release to Test PyPI.
        # I.e. A MERGE has been made into @spacetelescope/astrocut/main
        steps:
            - name: Git checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Make the test.pypi release tag
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  TAG=$(date + '%Y%m%d%H%M%S')
                  git tag $TAG

    # Release to Test PyPI
    publish-to-test-pypi:
        uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
        name: Publish to Test PyPI
        needs: make_tag
    
        with:
            # We DON'T want to upload to the official PyPI for this job
            repository_url: https://test.pypi.org/legacy/
        secrets:
            pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
